### PR TITLE
Fixed number of vectors for host notification suppressed event 

### PR DESCRIPTION
**Pull request by jdumalaonITRS**
This commit fixes the number of vectors for host notification
suppressed events in showlog tool. The previous value of 1
causes the entire message to be treated as the host name 
causing the log to be dropped from the results when filtered by
host name. 

This commit fixes MON-12796.

Signed-off-by: Jerson Dumalaon <jdumalaon@itrsgroup.com>

### CODE REVIEW

**Review by erikdsjostrom — APPROVED** [review]
Looks good to me! Just remember to squash the commits! :+1:

**Comment by jacobbaungard** [comment]
Can you please update the changelog with the information about the fix?

It would also be nice if the commit/pr message was a little more verbose, explaining why increasing the number of vectors fixes the problem - that would make it easier to review also.

**Comment by jdumalaonITRS** [comment]
Updated the changelog and PR description and will squash the commit at merge time.

**Review by jacobbaungard — APPROVED** [review]
Great, thanks! Looks good

**Pull request merged**
