### PR TITLE
Adding a threshold argument to `mon check distribution`

### PR DESCRIPTION
**Pull request by FracKenA**
adding threshold options for mon check distribution.

### CODE REVIEW

**Review by jacobbaungard — CHANGES_REQUESTED** [review]
Thanks for sending this in Ken!

Could you please have a look at the following and improve the commit message a bit: https://chris.beams.io/posts/git-commit/ . Also please add the JIRA key (MON-12517) to the commit message.

Secondly, please make sure the indentation in the file is consistent. The rest of the file uses tabs but you have changed the whole function to space indentation. This also makes it a little harder to review as the diff is larger than it needs to.

**Comment by FracKenA** [comment]
Copy that, will get it addressed.

**Comment by FracKenA** [comment]
Corrected the requested changes.

**Comment by jacobbaungard** [comment]
Thanks @FracKenA - I just fixed some spacing issues, but otherwise looks good.

I will merge once the build is finished.

**Review by jacobbaungard — APPROVED** [review]

**Pull request merged**
